### ISSUE TITLE
Not an issue - I want to thank you!

### ISSUE THREAD

**Issue by MadnessExpress** [radthebrown/ruby_cleverbot#2]
I tried every well know ruby api for cleverbot that I could find, and they have all been dead for years, but then I stumbled across your repo here, and it works flawlessly. Thank you so much for putting time and effort into this. I starred the repo, and I will be spreading the word to anyone searching for a working cleverbot api. Thank you so much!

**Comment by ltdgarcia** [comment]
Thank you, i really appreciate it
